<div class="col2-set thismonthorders">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Amount spent this month') ?></h3>
            </div>
            <div class="box-content">
                <p>
                    You have spent <span style="color: #25bce9;"><?php echo $this->getPopupContent()[0]; ?> AED</span> this month.You will have <span style="color: #25bce9;"><?php echo $this->getPopupContent()[1]; ?> </span> discount next month.
                </p>
                <p class="note">* The number indicates only the amount spent on completed orders.</p>
            </div>
        </div>
    </div>
</div>
